# Default Countryblock
default["apache"]["php_errors"] = "Off"
default["apache"]["mpm"] = "prefork"
default['apache']['allow_external'] = "false"
default["php"]["directives"]["post_max_size"] = "8M"
default["php"]["directives"]["upload_max_filesize"] = "20M"
# Default settings for prworld
default["prworld"]["prworld_install"] = "false"
default['prworld']['prworld_version'] = "3.2.3-1"
default["prworld"]["product_installations"] = { "classflow_marketing" => "true", "prometheanworld" => "false" }
default["prworld"]["prworldservername"] = "localhost"
default["prworld"]["path_exclude_list"] = "html|server-status|maintenance|autodiscover|prmaintenance|error"
default["prworld"]["prworld_log_rotation"] = "false"
default["prworld"]["prworlddbname"] = "prworlddbname"
default["prworld"]["prworlddbuser"] = "prworlddbuser"
default["prworld"]["prworlddbpass"] = "prworlddbpass"
default["prworld"]["prworld_backup"] = "false"
default['prworld']['prmaintenance_bypass'] = "bypass.prometheanworld.com"
default['prworld']['baseurl'] = "baseurl"
default['prworld']['clientid'] = "clientid"
default['prworld']['clientsecret'] = "clientsecret"
default['prworld']['username'] = "username"
default['prworld']['password'] = "password"
default['prworld']['oldimgdomain'] = "//c.cs24.content.force.com/"
default['prworld']['newimgdomain'] = "//test-promethean.cs24.force.com/"
default['prworld']['newsdateformat_version'] = "0.0.0-1"
default['prworld']['deflate'] = "true"
default['applications']['prmaint_version'] = "0.0.0-1"
default['applications']['cmsplugin']['prmaint_version'] = "0.0.0-1"
default['prworld']['emailfrom'] = "emailfrom"
default['prworld']['support_emailfrom'] = "support_emailfrom"
default['prworld']['sslRedirect'] = "true"
default['prworld']['bundleretain'] = "15"
default['prworld']['java_max_mem'] = "1G"
# Default settings for support mega site
default['supportmega']["supportmega_install"] = "false"
default['supportmega']["supportmegaservername"] = "localhost"
default['supportmega']['sslRedirect'] = "false"
# Default settings for prometheankb
default['prometheankb']["prometheankb_install"] = "false"
default['prometheankb']["prometheankbservername"] = "localhost"
# Default settings for activwallsystem
default["activwallsystem"]["aw_install"] = "false"
default["activwallsystem"]["aw_server"] = "localhost"
default["activwallsystem"]["aw_sslredirect"] = "false"
# Default settings for Planet
default['planet']['planet_url'] = "dev.prometheanplanet.com"
default['planet']['planet_alias'] = "dev1.prometheanplanet.com"
default['prworld']['planet_install'] = "false"
